name: Gofi Prebuild

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - run: go env -w GO111MODULE=on

      # 获取触发TAG
      - name: Obtain Trigger Tag
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # 打印触发TAG
      - name: Echo Trigger Tag
        run: echo Trigger tag is ${{ steps.tag.outputs.VERSION }}

      # 检出对应TAG的代码
      - name: Checkout Trigger Branch
        uses: actions/checkout@v2

      # 执行构建脚本
      - name: Excute Build Script
        run: ./gradlew

      # 列出产物
      - name: List output
        run: du -ah ./output

      # # 上传临时编译产物
      # - name: Upload Snapshot Build Product
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: Snapshot
      #     path: ./output
