name: Prebuild

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 配置Golang环境
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.5"
      - run: go env -w GO111MODULE=on

      # 配置Node环境
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: node -v
      - run: yarn -v

      # 检出代码
      - name: Checkout Trigger Branch
        uses: actions/checkout@v2

      # 执行构建脚本
      - name: Excute Build Script
        run: yarn && yarn build

      # 列出产物
      - name: List output
        run: du -ah ./output
