name: Gofi Release

on:
  create:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - run: go env -w GO111MODULE=on

      # 获取触发TAG
      - name: Obtain Trigger Tag
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # 打印触发TAG
      - name: Echo Trigger Tag
        run: echo Trigger tag is ${{ steps.tag.outputs.VERSION }}

      # 检出对应TAG的代码
      - name: Checkout Trigger Branch
        uses: actions/checkout@v2

      # 执行构建脚本
      - name: Excute Build Script
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: ./gradlew
        
      # 列出产物
      - name: List output
        run: du -ah ./output      
        
      # # 压缩产物
      # - name: Compress
      #   uses: docker://gact/upx:latest
      #   with:
      #     dir: './output'
      #     upx_args: '-9'

      # 创建新的发布
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.VERSION }}
          release_name: Release ${{ steps.tag.outputs.VERSION }}
          draft: false
          prerelease: false

      # 上传构建产物到发布
      - name: Upload Build Outputs
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./output/gofi-darwin-10.12-amd64
            ./output/gofi-linux-amd64
            ./output/gofi-linux-arm-5
            ./output/gofi-windows-4.0-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
