name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 安装go
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      # 检出对应TAG的代码
      - name: Checkout Trigger Branch
        uses: actions/checkout@v2

      # 执行构建脚本
      - name: Excute Unit Test
        run: ./test.sh
